Session-23/Session-23/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Session_23.EF;
using Session_23.EF.Repositories;
using Session_23.Model;
using Session_23.Models.Customer;

namespace Session_23.Controllers {
    public class CustomerController : Controller {

        private readonly IEntityRepo<Transaction> _transactionRepo;
        private readonly IEntityRepo<Customer> _customerRepo;
        private readonly IEntityRepo<Employee> _employeeRepo;
        private readonly IEntityRepo<Pet> _petRepo;
        private readonly IEntityRepo<PetFood> _petFoodRepo;


        public CustomerController(IEntityRepo<Transaction> transactionRepo, IEntityRepo<Customer> customerRepo, IEntityRepo<Employee> employeeRepo, IEntityRepo<Pet> petRepo, IEntityRepo<PetFood> petFoodRepo) {
            _customerRepo = customerRepo;
            _transactionRepo = transactionRepo;
            _employeeRepo = employeeRepo;
            _customerRepo = customerRepo;
            _petRepo = petRepo;
            _petFoodRepo = petFoodRepo;
        }


        // GET: CustomerController
        public ActionResult Index() {

            var customers = _customerRepo.GetAll();
            return View(model: customers);
        }


        // GET: CustomerController/Details/5 
        public ActionResult Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var customer = _customerRepo.GetById(id.Value);
            if (customer == null) {
                return NotFound();
            }

            try { 
            GetDataForCustomer(customer);
            }
            catch {

            }

            var viewCustomer = new CustomerDetailsDto {
                Id = customer.Id,
                Name = customer.Name,
                Surname = customer.Surname,
                Phone = customer.Phone,
                Tin = customer.Tin,
                Transactions = customer.Transactions.ToList()
            };
            return View(model: viewCustomer);
        }


        // GET: CustomerController/Create
        public ActionResult Create() {

            return View();
        }


        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CustomerCreateDto customer) {

            if (!ModelState.IsValid) {
                return View();
            }

            var dbCustomer = new Customer(customer.Name, customer.Surname, customer.Phone, customer.Tin);

            _customerRepo.Add(dbCustomer);
            return RedirectToAction("Index");

        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id) {

            var dbCustomer = _customerRepo.GetById(id);
            if (dbCustomer == null) {
                return NotFound();
            }

            var viewCustomer = new CustomerEditDto() {
                Name = dbCustomer.Name,
                Surname = dbCustomer.Surname,
                Phone = dbCustomer.Phone,
                Tin = dbCustomer.Tin,
            };
            return View(model: viewCustomer);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CustomerEditDto customer) {

            if (!ModelState.IsValid) {
                return View();
            }

            var dbCustomer = _customerRepo.GetById(id);
            if (dbCustomer == null) {
                return NotFound();
            }
            dbCustomer.Name = customer.Name;
            dbCustomer.Surname = customer.Surname;
            dbCustomer.Phone = customer.Phone;
            dbCustomer.Tin = customer.Tin;

            _customerRepo.Update(id, dbCustomer);

            return RedirectToAction("Index");
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id) {

            var dbCustomer = _customerRepo.GetById(id);
            if (dbCustomer == null) {
                return NotFound();
            }

            var viewCustomer = new CustomerDeleteDto() {
                Name = dbCustomer.Name,
                Surname = dbCustomer.Surname,
                Phone = dbCustomer.Phone,
                Tin = dbCustomer.Tin,
                Id = dbCustomer.Id
            };
            return View(model: viewCustomer);
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {

            try {
                _customerRepo.Delete(id);
            }
            catch {
                 return View("~/Views/Shared/ErrorDelete.cshtml");
            }


            return RedirectToAction("Index");
        }


        //helpers
        public void GetDataForCustomer(Customer customer) {
            foreach (var transaction in customer.Transactions.ToList()) {
                transaction.Employee = _employeeRepo.GetById(transaction.EmployeeId);
                transaction.Pet = _petRepo.GetById(transaction.PetId);
                transaction.PetFood = _petFoodRepo.GetById(transaction.PetFoodId);
            }
        }
    }
}

Session-23/Session-23/Controllers/PetController.cs
using Microsoft.AspNetCore.Mvc;
using Session_23.EF;
using Session_23.EF.Repositories;
using Session_23.Model;
using Session_23.Models.Employee;
using Session_23.Models.Pet;

namespace Session_23.Controllers {
    public class PetController : Controller {

        private readonly IEntityRepo<Transaction> _transactionRepo;
        private readonly IEntityRepo<Customer> _customerRepo;
        private readonly IEntityRepo<Employee> _employeeRepo;
        private readonly IEntityRepo<Pet> _petRepo;
        private readonly IEntityRepo<PetFood> _petFoodRepo;


        public PetController(IEntityRepo<Transaction> transactionRepo, IEntityRepo<Customer> customerRepo, IEntityRepo<Employee> employeeRepo, IEntityRepo<Pet> petRepo, IEntityRepo<PetFood> petFoodRepo) {
            _customerRepo = customerRepo;
            _transactionRepo = transactionRepo;
            _employeeRepo = employeeRepo;
            _customerRepo = customerRepo;
            _petRepo = petRepo;
            _petFoodRepo = petFoodRepo;
        }



        // GET: PetController
        public ActionResult Index() {

            var pets = _petRepo.GetAll();
            return View(model: pets);
        }


        // GET: PetController/Details/5 
        public ActionResult Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var pet = _petRepo.GetById(id.Value);
            if (pet == null) {
                return NotFound();
            }

            try { GetDataForPet(pet); } catch { }

            var viewPet = new PetDetailsDto {
                Id = pet.Id,
                AnimalType= pet.AnimalType,
                Breed= pet.Breed,
                Cost= pet.Cost,
                PetStatus= pet.PetStatus,
                Price= pet.Price,
                Transactions = pet.Transactions.ToList()
            };
            return View(model: viewPet);
        }


        // GET: PetController/Create
        public ActionResult Create() {

            return View();
        }


        // POST: PetController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PetCreateDto pet) {

            if (!ModelState.IsValid) {
                return View();
            }
            var dbPet = new Pet(pet.Breed, pet.AnimalType, pet.PetStatus, pet.Price, pet.Cost);
            _petRepo.Add(dbPet);
            return RedirectToAction("Index");

        }

        // GET: PetController/Edit/5
        public ActionResult Edit(int id) {

            var dbPet = _petRepo.GetById(id);
            if (dbPet == null) {
                return NotFound();
            }

            var viewPet = new PetEditDto() {
                Breed = dbPet.Breed,
                AnimalType = dbPet.AnimalType,
                PetStatus = dbPet.PetStatus,
                Price = dbPet.Price,
                Cost = dbPet.Cost
            };
            return View(model: viewPet);
        }

        // POST: PetController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PetEditDto pet) {

            if (!ModelState.IsValid) {
                return View();
            }

            var dbPet = _petRepo.GetById(id);
            if (dbPet == null) {
                return NotFound();
            }
            dbPet.Breed = pet.Breed;
            dbPet.AnimalType = pet.AnimalType;
            dbPet.PetStatus = pet.PetStatus;
            dbPet.Price = pet.Price;
            dbPet.Cost = pet.Cost;


            _petRepo.Update(id, dbPet);

            return RedirectToAction("Index");
        }

        // GET: PetController/Delete/5
        public ActionResult Delete(int id) {

            var dbPet = _petRepo.GetById(id);
            if (dbPet == null) {
                return NotFound();
            }

            var viewPet = new PetDeleteDto() {
                Breed = dbPet.Breed,
                AnimalType = dbPet.AnimalType,
                PetStatus = dbPet.PetStatus,
                Price = dbPet.Price,
                Cost = dbPet.Cost,
                Id = dbPet.Id

            };
            return View(model: viewPet);
        }

        // POST: PetController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {


            try {
                _petRepo.Delete(id);
            }
            catch {

                return View("~/Views/Shared/ErrorDelete.cshtml");
            }


            return RedirectToAction("Index");
        }

        public void GetDataForPet(Pet pet) {
            foreach (var transaction in pet.Transactions.ToList()) {
                transaction.Customer = _customerRepo.GetById(transaction.CustomerId);
                transaction.Employee = _employeeRepo.GetById(transaction.EmployeeId);
                transaction.PetFood = _petFoodRepo.GetById(transaction.PetFoodId);
            }
        }
    }
}

Session-23/Session-23/Controllers/PetFoodController.cs
using Microsoft.AspNetCore.Mvc;
using Session_23.EF;
using Session_23.Model;
using Session_23.Models.PetFood;

namespace Session_23.Controllers {
    public class PetFoodController : Controller {

        private readonly IEntityRepo<Transaction> _transactionRepo;
        private readonly IEntityRepo<Customer> _customerRepo;
        private readonly IEntityRepo<Employee> _employeeRepo;
        private readonly IEntityRepo<Pet> _petRepo;
        private readonly IEntityRepo<PetFood> _petFoodRepo;


        public PetFoodController(IEntityRepo<Transaction> transactionRepo, IEntityRepo<Customer> customerRepo, IEntityRepo<Employee> employeeRepo, IEntityRepo<Pet> petRepo, IEntityRepo<PetFood> petFoodRepo) {
            _customerRepo = customerRepo;
            _transactionRepo = transactionRepo;
            _employeeRepo = employeeRepo;
            _customerRepo = customerRepo;
            _petRepo = petRepo;
            _petFoodRepo = petFoodRepo;
        }


        // GET: PetFoodController
        public ActionResult Index() {

            var petFoods = _petFoodRepo.GetAll();
            return View(model: petFoods);
        }


        // GET: PetFoodController/Details/5 
        public ActionResult Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var petFood = _petFoodRepo.GetById(id.Value);
            if (petFood == null) {
                return NotFound();
            }

            try { GetDataForPetFood(petFood); } catch { }

            var viewPetFood = new PetFoodDetailsDto {
                Id = petFood.Id,
                AnimalType = petFood.AnimalType,
                Cost = petFood.Cost,
                Price = petFood.Price,
                Transactions = petFood.Transactions.ToList()
            };
            return View(model: viewPetFood);
        }


        // GET: PetFoodController/Create
        public ActionResult Create() {

            return View();
        }


        // POST: PetFoodController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PetFoodCreateDto petFood) {

            if (!ModelState.IsValid) {
                return View();
            }
            var dbPetFood = new PetFood(petFood.AnimalType, petFood.Price, petFood.Cost);

            var petFoodType = petFood.AnimalType;
            var existingPetFoods = _petFoodRepo.GetAll();
            bool petFoodExists = false;

            foreach(var food in existingPetFoods) {
                if (food.AnimalType == petFoodType) {
                    petFoodExists = true;
                }
            }
            if (!petFoodExists) {
                _petFoodRepo.Add(dbPetFood);
                return RedirectToAction("Index");
            } else {
                return View("~/Views/Shared/ErrorMessage.cshtml");
            }

        }

        // GET: PetFoodController/Edit/5
        public ActionResult Edit(int id) {

            var dbPetFood = _petFoodRepo.GetById(id);
            if (dbPetFood == null) {
                return NotFound();
            }

            var viewPetFood = new PetFoodEditDto() {
                AnimalType = dbPetFood.AnimalType,
                Price = dbPetFood.Price,
                Cost = dbPetFood.Cost
            };
            return View(model: viewPetFood);
        }

        // POST: PetFoodController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PetFoodEditDto petFood) {

            if (!ModelState.IsValid) {
                return View();
            }

            var dbPetFood = _petFoodRepo.GetById(id);
            if (dbPetFood == null) {
                return NotFound();
            }
            dbPetFood.AnimalType = petFood.AnimalType;
            dbPetFood.Price = petFood.Price;
            dbPetFood.Cost = petFood.Cost;


            _petFoodRepo.Update(id, dbPetFood);

            return RedirectToAction("Index");
        }

        // GET: PetFoodController/Delete/5
        public ActionResult Delete(int id) {

            var dbPetFood = _petFoodRepo.GetById(id);
            if (dbPetFood == null) {
                return NotFound();
            }

            var viewPetFood = new PetFoodDeleteDto() {
                AnimalType = dbPetFood.AnimalType,
                Price = dbPetFood.Price,
                Cost = dbPetFood.Cost,
                Id = dbPetFood.Id

            };
            return View(model: viewPetFood);
        }

        // POST: PetFoodController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection) {
            try {
                _petFoodRepo.Delete(id);
            }
            catch {

                return View("~/Views/Shared/ErrorDelete.cshtml");
            }


            return RedirectToAction("Index");
        }


        //HELPERS
        public void GetDataForPetFood(PetFood petFood) {
            foreach (var transaction in petFood.Transactions.ToList()) {
                transaction.Customer = _customerRepo.GetById(transaction.CustomerId);
                transaction.Employee = _employeeRepo.GetById(transaction.EmployeeId);
                transaction.Pet = _petRepo.GetById(transaction.PetId);
            }
        }
    }
}

Session-23/Session-23/Views/Shared/ErrorDelete.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error Delete";
}

<h1 class="text-danger">Error.</h1>
<p class="text-danger">You can not perform that delete request. Please check the relations of the object!</p>

Session-23/Session-23/Views/Shared/ErrorMessage.cshtml
@model ErrorViewModel
@{
    ViewData["Title"] = "Error Delete";
}

<h1 class="text-danger">Error.</h1>
<p class="text-danger">You can not perform that delete request. Please try again or contact administrator!</p>

Session-23/Session-23/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Session_23</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Session_23.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Session_23</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Pets</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PetFood" asp-action="Index">Pet Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MonthlyLedger" asp-action="Index">Monthy Ledger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Session_23 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>